# Generated by Django 5.2.3 on 2025-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeC', models.CharField(max_length=100)),
                ('emailC', models.EmailField(max_length=254)),
                ('categoria', models.CharField(max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
