# Generated by Django 5.2.3 on 2025-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.CharField(choices=[('PAC', 'PACIENTE'), ('MED', 'MÉDICO')], default='PAC', max_length=3),
        ),
    ]
