# Generated by Django 5.2.3 on 2025-08-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_alter_contato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='solicitanteC',
            field=models.CharField(choices=[('PAC', 'PACIENTE'), ('MED', 'MÉDICO')], default='PAC', max_length=3),
        ),
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.CharField(choices=[('SUP', 'Suporte'), ('CRI', 'Crítica'), ('OUT', 'Outros')], max_length=3),
        ),
    ]
