# Generated by Django 5.2.3 on 2025-08-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contato_solicitantec_alter_contato_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitanteS', models.CharField(choices=[('PAC', 'PACIENTE'), ('MED', 'MÉDICO')], default='PAC', max_length=3)),
                ('nomeS', models.CharField(max_length=100)),
                ('emailS', models.EmailField(max_length=254)),
                ('procedimentosS', models.CharField(choices=[('CO', 'Consulta'), ('EX', 'Exame'), ('RA', 'Radiografia')], default='CO', max_length=2)),
                ('convenio', models.CharField(choices=[('PU', 'Público'), ('PR', 'Privado'), ('EM', 'Empresarial')], default='PU', max_length=2)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
