# Generated by Django 5.2.3 on 2025-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_medico_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/avatars'),
        ),
    ]
