# Generated by Django 5.2 on 2025-06-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_paciente_cpf'),
        ('users', '0002_usuario_grupo'),
    ]

    operations = [
    ]
