# Generated by Django 5.2 on 2025-06-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_remove_paciente_cpf_0002_usuario_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
    ]
