# Generated by Django 5.2.3 on 2025-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='media/avatars'),
        ),
    ]
