# Generated by Django 5.2.3 on 2025-07-19 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_email_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\s]+$')], verbose_name='username'),
        ),
    ]
