# Generated by Django 5.2.3 on 2025-08-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeC', models.CharField(max_length=100)),
                ('emailC', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('', ' Selecione uma categoria '), ('duvida', 'Dúvida sobre medicamentos'), ('agendamento', 'Agendamento de consulta'), ('emergencia', 'Informação sobre emergência'), ('reclamacao', 'Reclamação'), ('critica', 'Crítica'), ('outro', 'Outro motivo')], max_length=20)),
                ('comentarios', models.TextField()),
            ],
        ),
    ]
