# Generated by Django 5.2.3 on 2025-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contato',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
