# Generated by Django 5.2.3 on 2025-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_contato_categoria_alter_contato_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
