# Generated by Django 5.2.3 on 2025-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_medico_crm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='crm',
        ),
        migrations.AddField(
            model_name='medico',
            name='crm_estado',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='crm_numero',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
