# Generated by Django 5.2.3 on 2025-08-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_contato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
