# Generated by Django 5.2.3 on 2025-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_contato_remove_medico_crm_medico_crm_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm_estado',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm_numero',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
