# Generated by Django 5.2.3 on 2025-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_medico_crm_estado_alter_medico_crm_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm_estado',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm_numero',
            field=models.CharField(unique=True),
        ),
    ]
