# Generated by Django 5.2.3 on 2025-08-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_contato_categoria'),
        ('users', '0015_alter_medico_crm_estado_alter_medico_crm_numero'),
    ]

    operations = [
    ]
