# Generated by Django 5.2.3 on 2025-09-07 13:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimentos', models.CharField(max_length=200)),
                ('convenio', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='AGENDADO', max_length=30, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medico', to='users.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_paciente', to='users.paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início da Consulta')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim da Consulta')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('motivo', models.TextField(blank=True, help_text='Motivo pelo qual o agendamento não pôde ser realizado.', null=True, verbose_name='Motivo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MarcarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='PEDIDO', max_length=30, null=True)),
                ('queixa', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('data_fim', models.DateTimeField(default=datetime.datetime.now)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agendadas', to='users.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='users.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='BloquearDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_escolhido', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-Feira'), (2, 'Terça-Feira'), (3, 'Quarta-Feira'), (4, 'Quinta-Feira'), (5, 'Sexta-Feira'), (6, 'Sábado')], verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Horário de Início do Bloqueio')),
                ('horario_fim', models.TimeField(blank=True, default=datetime.time(0, 0), null=True, verbose_name='Horário de Fim do Bloqueio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_bloqueado_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dia Bloqueado',
                'verbose_name_plural': 'Dias Bloqueados',
                'unique_together': {('dia_escolhido', 'usuario')},
            },
        ),
    ]
