# Generated by Django 5.2.3 on 2025-08-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarevento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='users.paciente'),
        ),
        migrations.CreateModel(
            name='CriarEventoPaciente',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente_evento', serialize=False, to='users.paciente')),
                ('status', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='PEDIDO', max_length=30, null=True)),
                ('queixa', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_evento', to='users.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
