# Generated by Django 5.2.3 on 2025-09-03 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueardia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_bloqueado_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='criarevento',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medico', to='users.medico'),
        ),
        migrations.AddField(
            model_name='criarevento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_paciente', to='users.paciente'),
        ),
        migrations.CreateModel(
            name='MarcarEvento',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente_evento', serialize=False, to='users.paciente')),
                ('status', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='PEDIDO', max_length=30, null=True)),
                ('queixa', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta_medico', to='users.medico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
