# Generated by Django 5.2.3 on 2025-09-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcarevento',
            name='procedimentos',
            field=models.CharField(blank=True, choices=[('', 'Selecione um Procedimento'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Retorno', 'Retorno')], default='Consulta', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='convenio',
            field=models.CharField(choices=[('', 'Selecione um Convênio'), ('Publico', 'Público'), ('Particular', 'Particular')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='procedimentos',
            field=models.CharField(choices=[('', 'Selecione um Procedimento'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Retorno', 'Retorno')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='marcarevento',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agendadas', to='users.medico'),
            preserve_default=False,
        ),
    ]
