# Generated by Django 5.2.3 on 2025-09-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueardia',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_bloqueado_medico', to='users.medico'),
        ),
        migrations.AddField(
            model_name='criaragendamento',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_medico', to='users.medico'),
        ),
        migrations.AddField(
            model_name='criaragendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to='users.paciente'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera_medico', to='users.medico'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera_paciente', to='users.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='bloqueardia',
            unique_together={('dia_escolhido', 'medico')},
        ),
    ]
