# Generated by Django 5.2.3 on 2025-07-25 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmember',
            old_name='eventos',
            new_name='events',
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('events', 'usuario')},
        ),
    ]
