# Generated by Django 5.2.3 on 2025-07-27 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_eventos_eventmember_events_and_more'),
        ('users', '0009_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimentos', models.CharField(max_length=200)),
                ('convenio', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.criarevento'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
