# Generated by Django 5.2.3 on 2025-09-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marcarevento_procedimentos_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarevento',
            name='queixa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='convenio',
            field=models.CharField(blank=True, choices=[('', 'Selecione um Convênio'), ('Publico', 'Público'), ('Particular', 'Particular')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medico', to='users.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='AGENDADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MarcarEvento',
        ),
    ]
