# Generated by Django 5.2.3 on 2025-07-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_criarevento_alter_eventmember_events_delete_event'),
        ('users', '0009_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='dashboard.criarevento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_evento', to='users.paciente')),
            ],
            options={
                'unique_together': {('eventos', 'paciente')},
            },
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
