# Generated by Django 5.2.3 on 2025-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_criarevento_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criareventopaciente',
            name='status',
            field=models.CharField(blank=True, choices=[('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='PEDIDO', max_length=30, null=True),
        ),
    ]
