# Generated by Django 5.2.3 on 2025-09-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_criarevento_queixa_alter_criarevento_convenio_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarevento',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_medico', to='users.medico'),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to='users.paciente'),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='procedimentos',
            field=models.CharField(choices=[('', 'Selecione um Procedimento'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Retorno', 'Retorno')], default='Consulta', max_length=200),
        ),
    ]
