# Generated by Django 5.2.3 on 2025-08-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_membroevento_delete_eventmember'),
        ('users', '0009_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarevento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='users.paciente'),
        ),
    ]
