# Generated by Django 5.2.3 on 2025-09-13 21:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_criarevento_disponivel_alter_criarevento_medico_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaespera',
            options={'verbose_name': 'Lista de Espera', 'verbose_name_plural': 'Listas de Espera'},
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='motivo',
        ),
        migrations.AddField(
            model_name='listaespera',
            name='convenio',
            field=models.CharField(blank=True, choices=[('', 'Selecione um Convênio'), ('Publico', 'Público'), ('Particular', 'Particular')], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaespera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='procedimentos',
            field=models.CharField(choices=[('', 'Selecione um Procedimento'), ('Consulta', 'Consulta'), ('Exame', 'Exame'), ('Retorno', 'Retorno')], default='Consulta', max_length=200),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='queixa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='convenio',
            field=models.CharField(choices=[('', 'Selecione um Convênio'), ('Publico', 'Público'), ('Particular', 'Particular')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera_medico', to='users.medico'),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera_paciente', to='users.paciente'),
        ),
    ]
