# Generated by Django 5.2.3 on 2025-09-14 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_listaespera_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueardia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloqueardia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bloqueardia',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloqueardia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
