# Generated by Django 5.2.3 on 2025-08-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_criarevento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarevento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Agendado'),
        ),
    ]
