# Generated by Django 5.2.3 on 2025-08-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_criarevento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criarevento',
            name='status',
        ),
    ]
