# Generated by Django 5.2.3 on 2025-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_criarevento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarevento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='AGENDADO', max_length=30),
        ),
    ]
