# Generated by Django 5.2.3 on 2025-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_criarevento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criarevento',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='criarevento',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='AGENDADO', max_length=30, null=True),
        ),
    ]
