# Generated by Django 5.2.3 on 2025-08-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_criarevento_options_alter_criarevento_status'),
        ('users', '0013_delete_contato_remove_medico_crm_medico_crm_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriarEventoPaciente',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente_evento', serialize=False, to='users.paciente')),
                ('status', models.CharField(blank=True, choices=[('PEDIDO', 'Pedido'), ('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido')], default='PEDIDO', max_length=30, null=True)),
                ('queixa', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_evento', to='users.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MembroEvento',
        ),
    ]
