# Generated by Django 5.2.3 on 2025-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_criareventopaciente_delete_membroevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarevento',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='AGENDADO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='criareventopaciente',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('PEDIDO', 'Pedido'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido'), ('AUSENTE', 'Ausente')], default='PEDIDO', max_length=30, null=True),
        ),
    ]
